<div
    class="last-flights">
    <div
        class="content-center">

        <h1
            class="h1_line">
            Последние совершенные рейсы
        </h1>

        <div
            class="last-flights-board__wrapper">
            <table
                class="last-flights-board">
                <thead>
                    <tr>
                        <th
                            class="last-flights-board__date">
                            Дата перелёта
                        </th>
                        <th>
                            Страна отправления
                        </th>
                        <th>
                            Страна назначения
                        </th>
                        <th
                            class="last-flights-board__model">
                            Модель самолёта
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>1</span>
                                <span>2</span>
                                <span>/</span>
                                <span>0</span>
                                <span>2</span>
                            </div>
                        </td>
                        <td
                            colspan="2">
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>Р</span>
                                <span>О</span>
                                <span>С</span>
                                <span>С</span>
                                <span>И</span>
                                <span>Я</span>
                                <span>-</span>
                                <span>Г</span>
                                <span>Е</span>
                                <span>Р</span>
                                <span>М</span>
                                <span>А</span>
                                <span>Н</span>
                                <span>И</span>
                                <span>Я</span>
                            </div>
                        </td>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>S</span>
                                <span>U</span>
                                <span>J</span>
                                <span>E</span>
                                <span>T</span>
                                <span>1</span>
                                <span>0</span>
                                <span>0</span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>1</span>
                                <span>2</span>
                                <span>/</span>
                                <span>0</span>
                                <span>2</span>
                            </div>
                        </td>
                        <td
                            colspan="2">
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>Р</span>
                                <span>О</span>
                                <span>С</span>
                                <span>С</span>
                                <span>И</span>
                                <span>Я</span>
                                <span>-</span>
                                <span>Г</span>
                                <span>Е</span>
                                <span>Р</span>
                                <span>М</span>
                                <span>А</span>
                                <span>Н</span>
                                <span>И</span>
                                <span>Я</span>
                            </div>
                        </td>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>S</span>
                                <span>U</span>
                                <span>J</span>
                                <span>E</span>
                                <span>T</span>
                                <span>1</span>
                                <span>0</span>
                                <span>0</span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>1</span>
                                <span>2</span>
                                <span>/</span>
                                <span>0</span>
                                <span>2</span>
                            </div>
                        </td>
                        <td
                            colspan="2">
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>Р</span>
                                <span>О</span>
                                <span>С</span>
                                <span>С</span>
                                <span>И</span>
                                <span>Я</span>
                                <span>-</span>
                                <span>Г</span>
                                <span>Е</span>
                                <span>Р</span>
                                <span>М</span>
                                <span>А</span>
                                <span>Н</span>
                                <span>И</span>
                                <span>Я</span>
                            </div>
                        </td>
                        <td>
                            <div
                                class="last-flights-board__char-wrapper">
                                <span>S</span>
                                <span>U</span>
                                <span>J</span>
                                <span>E</span>
                                <span>T</span>
                                <span>1</span>
                                <span>0</span>
                                <span>0</span>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
